/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/leosunmo/consularis/pkg/apis/consularis.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeConsulObjects implements ConsulObjectInterface
type FakeConsulObjects struct {
	Fake *FakeConsularisV1alpha1
	ns   string
}

var consulobjectsResource = schema.GroupVersionResource{Group: "consularis.io", Version: "v1alpha1", Resource: "consulobjects"}

var consulobjectsKind = schema.GroupVersionKind{Group: "consularis.io", Version: "v1alpha1", Kind: "ConsulObject"}

// Get takes name of the consulObject, and returns the corresponding consulObject object, and an error if there is any.
func (c *FakeConsulObjects) Get(name string, options v1.GetOptions) (result *v1alpha1.ConsulObject, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(consulobjectsResource, c.ns, name), &v1alpha1.ConsulObject{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ConsulObject), err
}

// List takes label and field selectors, and returns the list of ConsulObjects that match those selectors.
func (c *FakeConsulObjects) List(opts v1.ListOptions) (result *v1alpha1.ConsulObjectList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(consulobjectsResource, consulobjectsKind, c.ns, opts), &v1alpha1.ConsulObjectList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ConsulObjectList{}
	for _, item := range obj.(*v1alpha1.ConsulObjectList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested consulObjects.
func (c *FakeConsulObjects) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(consulobjectsResource, c.ns, opts))

}

// Create takes the representation of a consulObject and creates it.  Returns the server's representation of the consulObject, and an error, if there is any.
func (c *FakeConsulObjects) Create(consulObject *v1alpha1.ConsulObject) (result *v1alpha1.ConsulObject, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(consulobjectsResource, c.ns, consulObject), &v1alpha1.ConsulObject{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ConsulObject), err
}

// Update takes the representation of a consulObject and updates it. Returns the server's representation of the consulObject, and an error, if there is any.
func (c *FakeConsulObjects) Update(consulObject *v1alpha1.ConsulObject) (result *v1alpha1.ConsulObject, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(consulobjectsResource, c.ns, consulObject), &v1alpha1.ConsulObject{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ConsulObject), err
}

// Delete takes name of the consulObject and deletes it. Returns an error if one occurs.
func (c *FakeConsulObjects) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(consulobjectsResource, c.ns, name), &v1alpha1.ConsulObject{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeConsulObjects) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(consulobjectsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ConsulObjectList{})
	return err
}

// Patch applies the patch and returns the patched consulObject.
func (c *FakeConsulObjects) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ConsulObject, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(consulobjectsResource, c.ns, name, data, subresources...), &v1alpha1.ConsulObject{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ConsulObject), err
}
